name: CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:   
      - name: Pushes  file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source_file: 'main.pdf'
          destination_repo: 'cvaraujo/Webpage-Carlos-Unicamp'
          destination_folder: '.'
          user_email: 'carlosvdaraujo@gmail.com'
          user_name: 'cvaraujo'
          commit_message: 'Update CV'

