name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: download paper repo
        uses: actions/checkout@v1
      - name: build pdf 
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: ./ 
      - name: stash pdf
        run: |
          mv main.pdf $HOME # cache the file
      - name: Checkout to send
        uses: actions/checkout@v2
      - name: Pushes  file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source_file: 'main.pdf'
          destination_repo: 'ThomasDillanBM/Webpage-Carlos-Unicamp'
          user_email: 'carlosvdaraujo@gmail.com'
          user_name: 'cvaraujo'
          commit_message: 'Update CV'

