name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: download paper repo
        uses: actions/checkout@v1
      - name: build pdf 
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: ./ 
      - name: stash pdf
        run: |
          cp main.pdf $HOME # cache the file
      - name: ls
        run: |
          ls -la
          echo $HOME
          echo $(pwd)
      - name: Checkout to send
        uses: actions/checkout@v2
      - name: ls
        run: |
          ls -la
          echo $HOME
          echo $(pwd)

